openapi: 3.1.0
info:
  title: Scheduling Appointment API
  description: REST API for scheduling appointment
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /schedule:
    post:
      summary: Schedule appointment
      operationId: ScheduleAppointment
      requestBody:
        required: true
        content:
          application/json:
            example:
              serviceName: "ECG"
              date: "2023-11-15"
              time: "14:00"
              duration: 60
              location: "Jamaica Plain"
              patientName: "John Maker"
              docterName: "Lorem Ipsum"
      responses:
        '200':
          description: Successful scheduling
          content:
            application/json:
              example:
                message: "Appointment scheduled successfully"
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                error: "Invalid request body"

  /cancel/{id}:
    delete:
      summary: Cancel a scheduled appointment by ID
      operationId: CancelAppointment
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the scheduled appointment to be cancelled
          example: 123
          schema:
            type: integer
      responses:
        '200':
          description: Successful cancellation
          content:
            application/json:
              example:
                message: "Appointment cancelled successfully"
        '404':
          description: Not Found
          content:
            application/json:
              example:
                error: "Appointment not found"

  /update/{id}:
    put:
      summary: Update scheduled appointment by ID
      operationId: UpdateService
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the scheduled appointment to be updated
          example: 123
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            example:
              serviceName: "Updated appointment"
              date: "2023-11-16"
              time: "15:30"
              duration: 90
              location: "Jamaica Plain"
              patientName: "John Maker"
              docterName: "Lorem Ipsum"
      responses:
        '200':
          description: Successful update
          content:
            application/json:
              example:
                message: "Appointment information updated successfully"
        '404':
          description: Not Found
          content:
            application/json:
              example:
                error: "Appointment not found"

  /viewscheduled/{id}:
    get:
      summary: View scheduled appointment information by ID
      operationId: ViewScheduledAppointment
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the scheduled appointment to view information
          example: 123
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              example:
                serviceName: "ECG"
                date: "2023-11-15"
                time: "14:00"
                duration: 60
                location: "Jamaica Plain"
                patientName: "John Maker"
                docterName: "Lorem Ipsum"
        '404':
          description: Not Found
          content:
            application/json:
              example:
                error: "Appointment not found"

components:
  schemas:
    ScheduledService:
      type: object
      properties:
        serviceName:
          type: string
        date:
          type: string
          format: date
        time:
          type: string
          format: time
        duration:
          type: integer
        location:
          type: string
        patientName:
          type: string
        doctortName:
          type: string
    Message:
      type: object
      properties:
        message:
          type: string
    Error:
      type: object
      properties:
        error:
          type: string
